### ISSUE TITLE
Memory and Page Objects won't work in VSC

### ISSUE THREAD

**Issue by eugs** [qavajs/vscode#30]
_Illegal return statement_ error is returned

qava packages:

```
"@cucumber/cucumber": "^9.1.2",
    "@qavajs/cli": "^0.27.0",
    "@qavajs/console-formatter": "^0.2.1",
    "@qavajs/format-report-portal": "^0.9.2",
    "@qavajs/html-formatter": "^0.0.11",
    "@qavajs/memory": "^1.6.0",
    "@qavajs/po": "^1.4.0",
    "@qavajs/steps-files": "^0.0.6",
    "@qavajs/steps-memory": "^0.0.11",
    "@qavajs/steps-wdio": "^0.33.0",
    "@qavajs/template": "^0.8.2",
    "@qavajs/validation": "^0.0.5",
    "@qavajs/xunit-formatter": "^0.0.4",
```

<img width="837" alt="Screenshot 2024-04-08 at 17 49 24" src="https://github.com/qavajs/vscode/assets/29432117/a9e5433f-f646-4646-8558-525ec194cc5c">
<img width="849" alt="Screenshot 2024-04-08 at 17 49 37" src="https://github.com/qavajs/vscode/assets/29432117/2e02ffe8-b528-4b91-bd78-78cdfb62010b">

index.js for PO and Memory:
<img width="352" alt="Screenshot 2024-04-08 at 17 50 04" src="https://github.com/qavajs/vscode/assets/29432117/745c9c0f-be40-42f2-a269-af1f2560af50">
<img width="451" alt="Screenshot 2024-04-08 at 17 50 19" src="https://github.com/qavajs/vscode/assets/29432117/0d6a2eb4-d943-4cd6-9bbc-508ebb458632">

**Comment by AlexGalichenko** [comment]
Fixed in 0.7.1
